export const NEW_MESSAGE = 'NEW_MESSAGE';

export const NEW_USER = 'NEW_USER';

export const CORRECT_CREDENTIALS = 'CORRECT_CREDENTIALS';
export const INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS';
export const USER_REGISTERED = 'USER_REGISTERED';
